[BACKEND-616] Defaulting buildV9Directly to true
metamx/tranquility pull request #2
Opened 2017-02-23 18:21 UTC by gkc2104

[BACKEND-616] FIxed formatting

2017-02-23 18:24 UTC, drcrallen approved these changes

2017-02-23 19:11 UTC, isimonenko requested changes

2017-02-23 19:11 UTC, isimonenko commented on core/src/main/scala/com/metamx/tranquility/druid/DruidTuning.scala
> +<<<<<<< HEAD
Is it a merge conflict artifact?

2017-02-23 19:52 UTC, drcrallen commented on core/src/main/scala/com/metamx/tranquility/druid/DruidTuning.scala
> +<<<<<<< HEAD
ha! yeah, somehow that one got missed

2017-02-23 20:52 UTC, gkc2104 commented
@isimonenko thanks for pointing that out, resolved it

2017-02-23 23:10 UTC, logarithm commented on core/src/main/scala/com/metamx/tranquility/druid/DruidTuning.scala
> +<<<<<<< HEAD
We have to have automatic travis tests for all our projects to catch situations like this automatically

2017-02-24 00:54 UTC, isimonenko approved these changes

2017-02-24 18:22 UTC, merged