Optional TaskContext added to DruidBeamMaker
metamx/tranquility pull request #4
Opened 2017-03-06 16:19 UTC by dgolitsyn

2017-03-06 16:26 UTC, drcrallen reviewed
Unit tests?

2017-03-07 14:00 UTC, logarithm requested changes
Is `taskContext` intended to be used for other purposes except `label` ?

2017-03-07 14:00 UTC, logarithm commented on core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
> +      case other => Map.empty
if you are not interested in the case value you can replace it by `_`.

2017-03-07 14:00 UTC, logarithm commented on core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
> +    _taskContext: Option[Map[String, Any]] = None
`Map[String, Any]` might be replaced by `Dict`

2017-03-07 14:00 UTC, logarithm commented on core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
> +  taskContext: Map[String, Any] = Map.empty
`Map[String, Any]` might be a `Dict` (as we already use it for `druidTuningMap`)

2017-03-07 14:00 UTC, logarithm commented on core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
> +  taskContext: Map[String, Any] = Map.empty
Why do we need default value for `taskContext` when in `DruidBeams` we already have default value for `taskContext` variable?

2017-03-07 14:08 UTC, egor-ryashin approved these changes

2017-03-07 14:10 UTC, logarithm commented on core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
> +      case taskContext if taskContext.nonEmpty => Map("context" -> taskContext)
Using the same name in pattern matching as original value (on which we do pattern matching) is suspicious and in some cases might lead to errors.

2017-03-07 14:13 UTC, dgolitsyn commented on core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
> +  taskContext: Map[String, Any] = Map.empty
fixed

2017-03-07 14:13 UTC, dgolitsyn commented on core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
> +      case other => Map.empty
fixed

2017-03-07 14:13 UTC, dgolitsyn commented on core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
> +    _taskContext: Option[Map[String, Any]] = None
fixed

2017-03-07 14:38 UTC, logarithm approved these changes

2017-03-07 14:39 UTC, merged